### ISSUE TITLE
Zvuk, oscilator

### ISSUE THREAD

**Issue by LukeOnuke** [LukeOnuke/zapakovan-covek#1]
Koristeci : https://stackoverflow.com/questions/39200994/how-to-play-a-specific-frequency-with-javascript
napraviti sawtooth oscilator za motor

**Comment by punishedhairpin** [comment]
https://www.circuitbasics.com/what-are-sawtooth-and-triangle-wave-generators/

**Comment by punishedhairpin** [comment]
vrlo zanimljiv metod fizike hvala bogu da kod postoji

**Comment by monkeypng** [comment]
https://drive.google.com/drive/folders/1VJM3CVxIRQTNhPdgNiRGBeUULY5WPv4B?usp=sharing
